theme = "mike.place"
baseurl = "https://mike.place/"
title = "mike.place"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
MetaDataFormat = "toml"
[indexes] 
    category = "categories"
    tag = "tags"
[author] 
    name = "Mike Lee Williams"
[permalinks]
    post = "/:year/:slug/"
    page = "/:slug/"
[params]
  description = "The website of Mike Lee Williams"
[markup.highlight]
style = "monokailight"
[markup.goldmark.renderer]
unsafe= true
